version: '3.4'

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile.development
    depends_on:
      - db
    entrypoint: /bin/bash
    environment:
      - DB_URL="db:5432"
    user: ${USER}
    volumes:
      - ./:/usr/src/app

  db:
    container_name: db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=automation-calculator-password
      - POSTGRES_DB=automation-calculator-development
    image: postgres:10.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: