# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    environment:
       - USER: "circleci"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      # build test image to test
      - run:
          name: ./go build ci
          command: ./go build ci
      
      # run tests!
      - run:
          name: ./go test ci
          command: ./go test ci

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    machine:
      enabled: true

    working_directory: ~/repo

    environment:
      - HEROKU_APP: automation-calculator-rails

    steps:
      - checkout

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - run:
          name: Login to heroku container registry
          command: heroku container:login

      - run:
          name: Push CI image to Heroku
          command: heroku container:push ci --recursive

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
