# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build_and_verify:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    environment:
       - USER: "circleci"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      # build test image to test
      - run:
          name: ./go build ci
          command: ./go build ci

      # lint
      - run:
          name: ./go lint ci
          command: ./go lint ci

      # run tests!
      - run:
          name: ./go test ci
          command: ./go test ci

      # login to docker hub and push image
      - run:
          name: Login to Docker Hub
          command: docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASSWORD

      - run:
          name: Create container tag
          command: export CONTAINER_TAG=$SEMVER_MAJOR_VERSION.$SEMVER_MINOR_VERSION.$SEMVER_PATCH-$CIRCLE_BUILD_NUM && echo $CONTAINER_TAG

      - run:
          name: Set container image and tag
          command: export CONTAINER_IMAGE=automationcalculator/automation-calculator-rails:$CONTAINER_TAG && echo $CONTAINER_IMAGE

      - run:
          name: Tag constructed image correctly
          command: docker tag automationcalculator_dev $CONTAINER_IMAGE

      - run:
          name: Upload docker image
          command: docker push $CONTAINER_IMAGE

  deploy:
    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_verify
      - deploy:
          requires:
            - build_and_verify
